 name: Bash CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Vérif syntaxe bash (rapide)
      - name: Bash syntax check
        run: |
          bash -n scripts/protect_mitm.sh

      # Installe ShellCheck (lint sécurité/meilleures pratiques)
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: ShellCheck lint
        run: |
          shellcheck --severity=style --color=always scripts/protect_mitm.sh

      # (Optionnel) Vérifier l’entête + droits exécutable
      - name: Ensure shebang + executable bit
        run: |
          grep -q '^#!/usr/bin/env bash' scripts/protect_mitm.sh
          chmod +x scripts/protect_mitm.sh

      # (Optionnel) Formatage avec shfmt – échoue si non formaté
      - name: Check formatting with shfmt
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          ~/go/bin/shfmt -d -i 2 -ci -sr scripts/protect_mitm.sh